-- ============================================================================
-- The 50 seed exercises.
--
-- Brief §11: "Fifty done properly beats five hundred done badly." Coverage is
-- by movement pattern, not by muscle popularity — horizontal and vertical push
-- and pull, squat, hinge, lunge, carry, and enough isolation work that every
-- seeded muscle has at least one exercise where it is the primary mover. A
-- muscle with an empty exercise panel is a visible hole in the anatomy feature.
--
-- `cues` is required by a CHECK constraint on every row, because it is the
-- offline fallback for "how do I do this lift" when a YouTube embed cannot
-- load in a basement (Brief §7).
--
-- `video_provider` is 'none' throughout. The brief calls for YouTube
-- placeholders, but a made-up video ID renders as a broken player, which is
-- worse than the text-only state the offline path already handles well. Real
-- IDs go in when someone has actually watched each video and confirmed it
-- teaches the lift. See DECISIONS.md ADR-0024.
--
-- `joint_count = 1` implies `mechanic = 'isolation'` and vice versa — a CHECK
-- constraint enforces it, so a few entries may look surprising. The barbell hip
-- thrust is single-joint (the knees hold an isometric angle), so by the brief's
-- own definition it is isolation, however compound it feels under a heavy bar.
-- ============================================================================

insert into public.exercises
  (slug, name, aliases, mechanic, force, joint_count, difficulty, is_unilateral,
   is_time_based, instructions, cues, common_mistakes,
   default_rep_low, default_rep_high, default_rest_seconds, popularity_rank)
values

-- --- Horizontal push ---------------------------------------------------------
('barbell-bench-press', 'Barbell Bench Press',
 array['bench','bp','flat bench','bench press'], 'compound', 'push', 2, 'intermediate', false, false,
 array['Lie back with eyes under the bar and feet flat on the floor.',
       'Grip slightly wider than shoulder width and squeeze the bar.',
       'Unrack, lower to mid chest with control, then press back up.'],
 array['Chest up','Elbows about 45 degrees','Drive your feet into the floor'],
 array['Bouncing the bar off the chest','Flaring the elbows straight out to the sides'],
 5, 8, 180, 10),

('incline-barbell-press', 'Incline Barbell Press',
 array['incline bench','incline bp'], 'compound', 'push', 2, 'intermediate', false, false,
 array['Set the bench to roughly 30 degrees.',
       'Unrack and lower the bar to the upper chest.',
       'Press up and slightly back over the shoulders.'],
 array['Stay tight against the bench','Bar to the collarbone, not the throat'],
 array['Setting the bench too steep, which turns it into a shoulder press'],
 6, 10, 150, 60),

('dumbbell-bench-press', 'Dumbbell Bench Press',
 array['db bench','dumbbell press','db press'], 'compound', 'push', 2, 'beginner', false, false,
 array['Sit with the dumbbells on your thighs, then kick them back as you lie down.',
       'Lower until your upper arms are level with your torso.',
       'Press up and slightly together.'],
 array['Wrists stacked over elbows','Control the descent'],
 array['Letting the dumbbells drift too far apart at the bottom'],
 8, 12, 120, 40),

('incline-dumbbell-press', 'Incline Dumbbell Press',
 array['incline db','incline dumbbell bench','incline db press'], 'compound', 'push', 2, 'beginner', false, false,
 array['Set the bench to roughly 30 degrees.',
       'Lower the dumbbells to chest level with elbows under the wrists.',
       'Press up until the arms are extended.'],
 array['Ribs down','Do not clash the dumbbells at the top'],
 array['Shrugging the shoulders up towards the ears'],
 8, 12, 120, 70),

('machine-chest-press', 'Machine Chest Press',
 array['chest press','machine press'], 'compound', 'push', 2, 'beginner', false, false,
 array['Set the seat so the handles sit at mid chest.',
       'Press out until the arms are extended without locking hard.',
       'Return under control until you feel a stretch.'],
 array['Shoulder blades back and down','Full range, no bouncing'],
 array['Seat set too high, which turns it into an incline press'],
 10, 15, 90, 120),

('push-up', 'Push-Up',
 array['pushup','press up'], 'compound', 'push', 2, 'beginner', false, false,
 array['Set your hands slightly wider than your shoulders.',
       'Brace your midsection so your body is one straight line.',
       'Lower your chest to just above the floor and press back up.'],
 array['Squeeze the glutes','Elbows back, not flared'],
 array['Letting the hips sag','Stopping short of the floor'],
 10, 20, 90, 30),

('chest-dip', 'Chest Dip',
 array['dip','dips','chest dips'], 'compound', 'push', 2, 'advanced', false, false,
 array['Support yourself on the bars with arms locked out.',
       'Lean the torso forward about 30 degrees.',
       'Lower until the upper arms are level, then press back up.'],
 array['Lean forward to bias the chest','Shoulders away from the ears'],
 array['Going deeper than the shoulders tolerate','Staying upright, which shifts the work to the triceps'],
 6, 12, 150, 90),

('cable-fly', 'Cable Fly',
 array['cable flye','cable crossover','crossover'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Set both pulleys at shoulder height or above.',
       'Step forward into a split stance with a slight elbow bend.',
       'Bring the handles together in front of the chest, then return under control.'],
 array['Fixed elbow angle throughout','Squeeze at the midline'],
 array['Turning it into a press by bending and extending the elbows'],
 12, 15, 75, 100),

('pec-deck', 'Pec Deck',
 array['machine fly','butterfly'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Set the seat so the handles are at chest height.',
       'Bring the pads together in front of you.',
       'Return until you feel a stretch, without letting the weight rest.'],
 array['Chest tall','Pause briefly at the squeeze'],
 array['Shrugging at the top of each rep'],
 12, 15, 75, 150),

-- --- Vertical push -----------------------------------------------------------
('overhead-press', 'Overhead Press',
 array['ohp','military press','standing press','shoulder press'], 'compound', 'push', 2, 'intermediate', false, false,
 array['Take the bar at collarbone height with a shoulder width grip.',
       'Brace the midsection and squeeze the glutes.',
       'Press overhead, moving the head back slightly, then bring it through at the top.'],
 array['Ribs down','Bar path close to the face','Finish with the bar over the ears'],
 array['Leaning back to turn it into an incline press'],
 5, 8, 180, 50),

('dumbbell-shoulder-press', 'Dumbbell Shoulder Press',
 array['db shoulder press','seated db press'], 'compound', 'push', 2, 'beginner', false, false,
 array['Sit with back support and the dumbbells at ear height.',
       'Press overhead until the arms are extended.',
       'Lower under control back to ear height.'],
 array['Wrists stacked over elbows','Do not arch the lower back'],
 array['Half repetitions that never reach ear height'],
 8, 12, 120, 80),

('lateral-raise', 'Lateral Raise',
 array['side raise','lat raise','dumbbell lateral raise'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Stand with the dumbbells at your sides and a slight elbow bend.',
       'Raise out to the sides until the arms are level with the shoulders.',
       'Lower slowly.'],
 array['Lead with the elbows','Stop at shoulder height'],
 array['Swinging the weight up with the lower back','Going far too heavy'],
 12, 20, 60, 45),

('rear-delt-fly', 'Rear Delt Fly',
 array['reverse fly','rear delt raise','bent over fly'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Hinge forward at the hips with a flat back.',
       'Let the dumbbells hang with a slight elbow bend.',
       'Raise out to the sides, leading with the elbows.'],
 array['Thumbs down slightly','Do not squeeze the shoulder blades hard'],
 array['Using the upper traps and turning it into a shrug'],
 12, 20, 60, 130),

('face-pull', 'Face Pull',
 array['facepull','rope face pull'], 'compound', 'pull', 2, 'beginner', false, false,
 array['Set a rope at roughly face height.',
       'Pull the rope towards your face, splitting the ends apart.',
       'Finish with the hands beside the ears and elbows high.'],
 array['Elbows above the wrists','Pull apart, not just back'],
 array['Setting the weight so heavy the torso rocks backwards'],
 12, 20, 60, 110),

-- --- Vertical pull -----------------------------------------------------------
('pull-up', 'Pull-Up',
 array['pullup','pull ups','wide grip pull up'], 'compound', 'pull', 2, 'advanced', false, false,
 array['Hang from the bar with an overhand grip, hands outside shoulder width.',
       'Pull your chest towards the bar, leading with the elbows.',
       'Lower until the arms are fully extended.'],
 array['Chest to the bar','Shoulders down away from the ears'],
 array['Kipping when the goal is strength','Stopping halfway down'],
 5, 10, 150, 20),

('chin-up', 'Chin-Up',
 array['chinup','chin ups','underhand pull up'], 'compound', 'pull', 2, 'advanced', false, false,
 array['Hang from the bar with an underhand grip at shoulder width.',
       'Pull until your chin clears the bar.',
       'Lower under control to a full hang.'],
 array['Drive the elbows down and back','Full hang at the bottom'],
 array['Cutting the bottom of the rep short'],
 5, 10, 150, 55),

('lat-pulldown', 'Lat Pulldown',
 array['pulldown','lat pull down'], 'compound', 'pull', 2, 'beginner', false, false,
 array['Set the thigh pad so you stay seated.',
       'Grip outside shoulder width and lean back slightly.',
       'Pull the bar to the upper chest, then return to a full stretch.'],
 array['Chest up, bar to the collarbone','Let the shoulder blades rise at the top'],
 array['Leaning back so far it becomes a row','Pulling behind the neck'],
 8, 12, 120, 25),

('straight-arm-pulldown', 'Straight-Arm Pulldown',
 array['straight arm pushdown','lat pushdown'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Stand facing a high pulley with a straight bar or rope.',
       'Keep the elbows almost locked and hinge slightly forward.',
       'Sweep the bar down to your thighs, then return overhead.'],
 array['Elbows stay fixed','Feel it in the armpit, not the triceps'],
 array['Bending the elbows and turning it into a pushdown'],
 12, 15, 75, 180),

-- --- Horizontal pull ---------------------------------------------------------
('barbell-row', 'Barbell Row',
 array['bent over row','bb row','pendlay row'], 'compound', 'pull', 2, 'intermediate', false, false,
 array['Hinge forward until the torso is about 45 degrees, back flat.',
       'Pull the bar to the lower ribs.',
       'Lower under control without letting the back round.'],
 array['Flat back throughout','Elbows past the ribs'],
 array['Standing up as the set gets hard','Yanking with the lower back'],
 6, 10, 150, 35),

('single-arm-dumbbell-row', 'Single-Arm Dumbbell Row',
 array['db row','one arm row','dumbbell row'], 'compound', 'pull', 2, 'beginner', true, false,
 array['Place one hand and the same-side knee on a bench.',
       'Let the dumbbell hang, then row it to your hip.',
       'Lower to a full stretch.'],
 array['Row to the hip, not the shoulder','Do not rotate the torso'],
 array['Turning the body to heave the weight up'],
 8, 12, 90, 65),

('seated-cable-row', 'Seated Cable Row',
 array['cable row','seated row','low row'], 'compound', 'pull', 2, 'beginner', false, false,
 array['Sit with a slight knee bend and a tall chest.',
       'Pull the handle to the navel, elbows close to the body.',
       'Return to a full stretch without rounding the back.'],
 array['Chest tall','Squeeze at the ribs'],
 array['Rocking the torso back and forth to move the weight'],
 10, 15, 90, 75),

('barbell-shrug', 'Barbell Shrug',
 array['shrug','shrugs','trap shrug'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Hold the bar at arm length in front of the thighs.',
       'Shrug the shoulders straight up towards the ears.',
       'Lower under control to a full stretch.'],
 array['Straight up and down','Pause at the top'],
 array['Rolling the shoulders, which adds nothing and irritates the joint'],
 10, 15, 90, 140),

-- --- Squat pattern -----------------------------------------------------------
('barbell-back-squat', 'Barbell Back Squat',
 array['squat','back squat','bs'], 'compound', 'push', 3, 'intermediate', false, false,
 array['Set the bar on the upper back and brace hard.',
       'Unrack, step back, and set your feet slightly wider than the hips.',
       'Sit down between your hips until the thighs are at least parallel, then drive up.'],
 array['Big breath, brace','Knees track over the toes','Drive the whole foot into the floor'],
 array['Letting the chest fall forward out of the hole','Cutting depth as the weight rises'],
 5, 8, 210, 5),

('barbell-front-squat', 'Front Squat',
 array['front squat','fs'], 'compound', 'push', 3, 'advanced', false, false,
 array['Rack the bar across the front delts with the elbows high.',
       'Squat down while keeping the torso upright.',
       'Drive up without letting the elbows drop.'],
 array['Elbows up','Stay tall through the chest'],
 array['Dropping the elbows, which dumps the bar forward'],
 5, 8, 210, 95),

('goblet-squat', 'Goblet Squat',
 array['goblet','kb squat'], 'compound', 'push', 3, 'beginner', false, false,
 array['Hold a dumbbell or kettlebell at chest height.',
       'Squat down between your knees, keeping the chest tall.',
       'Drive up through the whole foot.'],
 array['Elbows inside the knees at the bottom','Chest proud'],
 array['Letting the heels lift off the floor'],
 10, 15, 90, 85),

('leg-press', 'Leg Press',
 array['leg press machine'], 'compound', 'push', 2, 'beginner', false, false,
 array['Sit with the feet shoulder width on the platform.',
       'Lower until the knees reach about 90 degrees.',
       'Press back without locking the knees hard.'],
 array['Do not let the lower back round off the pad','Control the descent'],
 array['Bringing the knees so deep the pelvis tucks under'],
 10, 15, 120, 45),

('hack-squat', 'Hack Squat',
 array['machine hack squat'], 'compound', 'push', 2, 'intermediate', false, false,
 array['Set the shoulders under the pads with feet mid platform.',
       'Lower until the thighs are at least parallel.',
       'Drive back up through the whole foot.'],
 array['Back flat against the pad','Knees track over the toes'],
 array['Bouncing out of the bottom'],
 8, 12, 150, 115),

('bulgarian-split-squat', 'Bulgarian Split Squat',
 array['rear foot elevated split squat','rfess','bulgarian'], 'compound', 'push', 2, 'intermediate', true, false,
 array['Place the rear foot on a bench behind you.',
       'Lower until the front thigh is roughly parallel.',
       'Drive up through the front foot.'],
 array['Weight in the front heel','Torso slightly forward for the glutes'],
 array['Standing too close to the bench, which crowds the front knee'],
 8, 12, 120, 125),

('walking-lunge', 'Walking Lunge',
 array['lunge','lunges','walking lunges'], 'compound', 'push', 2, 'beginner', true, false,
 array['Step forward into a lunge until the back knee nearly touches the floor.',
       'Drive through the front foot to stand and step through.',
       'Alternate legs for the set.'],
 array['Torso upright','Long step for the glutes, short for the quads'],
 array['Letting the front knee collapse inwards'],
 10, 16, 120, 145),

('leg-extension', 'Leg Extension',
 array['knee extension','quad extension'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Set the pad just above the ankles.',
       'Extend the knees until the legs are straight.',
       'Lower under control without letting the weight rest.'],
 array['Pause briefly at the top','Slow on the way down'],
 array['Swinging the torso to start each rep'],
 12, 15, 75, 105),

-- --- Hinge pattern -----------------------------------------------------------
('conventional-deadlift', 'Conventional Deadlift',
 array['deadlift','dl','conventional dl'], 'compound', 'pull', 3, 'advanced', false, false,
 array['Set the mid foot under the bar with shins close.',
       'Hinge down, grip just outside the legs, and pull the slack out of the bar.',
       'Stand up by pushing the floor away, finishing tall.'],
 array['Flat back, chest up','Bar stays against the legs','Squeeze the glutes at the top'],
 array['Rounding the lower back','Jerking the bar off the floor'],
 3, 6, 240, 15),

('romanian-deadlift', 'Romanian Deadlift',
 array['rdl','stiff leg deadlift','romanian dl'], 'compound', 'pull', 2, 'intermediate', false, false,
 array['Stand tall holding the bar at the hips.',
       'Push the hips back, letting the bar slide down the thighs.',
       'Stop when the hamstrings are fully stretched, then drive the hips forward.'],
 array['Hinge at the hip, do not squat','Soft knees, not locked','Bar stays on the legs'],
 array['Bending the knees so much it becomes a deadlift','Rounding the upper back'],
 8, 12, 150, 30),

('trap-bar-deadlift', 'Trap Bar Deadlift',
 array['hex bar deadlift','trap bar dl'], 'compound', 'pull', 3, 'beginner', false, false,
 array['Stand inside the trap bar with feet hip width.',
       'Hinge down and take the handles.',
       'Stand up by driving the floor away.'],
 array['Chest up before you pull','Push the floor away'],
 array['Letting the hips shoot up first'],
 5, 8, 210, 100),

('barbell-hip-thrust', 'Barbell Hip Thrust',
 array['hip thrust','thrust'], 'isolation', 'push', 1, 'intermediate', false, false,
 array['Sit with the upper back against a bench and the bar over the hips.',
       'Drive the hips up until the torso is parallel to the floor.',
       'Lower under control without resting the bar on the floor.'],
 array['Chin tucked, ribs down','Squeeze the glutes hard at the top'],
 array['Hyperextending the lower back at the top instead of finishing with the glutes'],
 8, 12, 120, 135),

('lying-leg-curl', 'Lying Leg Curl',
 array['leg curl','hamstring curl','prone leg curl'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Lie face down with the pad just above the heels.',
       'Curl the heels towards your glutes.',
       'Lower slowly to a full stretch.'],
 array['Hips stay down on the pad','Slow negative'],
 array['Lifting the hips to swing the weight up'],
 10, 15, 75, 155),

('seated-leg-curl', 'Seated Leg Curl',
 array['seated hamstring curl'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Set the thigh pad snug and the ankle pad just above the heels.',
       'Curl the legs down and back as far as they go.',
       'Return under control.'],
 array['Push the thighs into the pad','Pause at the bottom'],
 array['Letting the weight snap back up'],
 10, 15, 75, 160),

('back-extension', 'Back Extension',
 array['hyperextension','45 degree back extension'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Set the pad just below the hip crease.',
       'Hinge down until you feel a hamstring stretch.',
       'Raise until the body is in a straight line.'],
 array['Stop at straight, do not arch past it','Squeeze the glutes at the top'],
 array['Hyperextending the spine at the top'],
 12, 15, 75, 190),

-- --- Calves ------------------------------------------------------------------
('standing-calf-raise', 'Standing Calf Raise',
 array['calf raise','standing calves'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Stand with the balls of the feet on the platform.',
       'Drop the heels for a full stretch.',
       'Rise onto the toes as high as you can.'],
 array['Pause at the top and the bottom','Full range, no bouncing'],
 array['Bouncing off the stretch using the tendon rather than the muscle'],
 10, 15, 60, 165),

('seated-calf-raise', 'Seated Calf Raise',
 array['seated calves','soleus raise'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Sit with the pad on the lower thighs and the balls of the feet on the platform.',
       'Drop the heels for a stretch.',
       'Rise onto the toes and squeeze.'],
 array['Knees bent shifts the work to the soleus','Slow and full range'],
 array['Using a range of motion of two centimetres'],
 12, 20, 60, 200),

-- --- Biceps ------------------------------------------------------------------
('barbell-curl', 'Barbell Curl',
 array['bb curl','bicep curl','straight bar curl'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Stand holding the bar at shoulder width, arms extended.',
       'Curl the bar to shoulder height keeping the elbows at your sides.',
       'Lower under control to full extension.'],
 array['Elbows pinned to the ribs','Full extension at the bottom'],
 array['Swinging the hips to start each rep'],
 8, 12, 90, 40),

('cable-woodchop', 'Cable Woodchop',
 array['woodchop','wood chop','cable chop','rotation'], 'isolation', 'pull', 1, 'intermediate', true, false,
 array['Set a cable at shoulder height and stand side on.',
       'Take the handle in both hands with the arms almost straight.',
       'Rotate through the trunk and pull across the body, then return slowly.'],
 array['Turn through the ribs, not the arms','Hips stay square to the front'],
 array['Pulling with the arms instead of rotating the torso'],
 10, 15, 75, 215),

('hammer-curl', 'Hammer Curl',
 array['neutral grip curl','hammer curls'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Hold the dumbbells with palms facing each other.',
       'Curl to shoulder height without rotating the wrists.',
       'Lower under control.'],
 array['Thumbs stay up throughout','Elbows still'],
 array['Rotating into a normal curl halfway up'],
 10, 15, 75, 120),

('preacher-curl', 'Preacher Curl',
 array['ez bar preacher curl','preacher'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Set the pad so the armpits rest on the top edge.',
       'Curl the bar up, stopping short of vertical to keep tension.',
       'Lower slowly until the arms are almost straight.'],
 array['Do not let the elbows lift off the pad','Control the stretch at the bottom'],
 array['Dropping the weight fast at the bottom, which strains the elbow'],
 10, 15, 90, 175),

-- --- Triceps -----------------------------------------------------------------
('close-grip-bench-press', 'Close-Grip Bench Press',
 array['cgbp','close grip bench'], 'compound', 'push', 2, 'intermediate', false, false,
 array['Grip the bar at roughly shoulder width.',
       'Lower to the lower chest with the elbows tucked.',
       'Press back up, driving with the triceps.'],
 array['Elbows tucked to about 30 degrees','Wrists stacked over elbows'],
 array['Gripping so narrow the wrists hurt'],
 6, 10, 150, 110),

('triceps-pushdown', 'Triceps Pushdown',
 array['pushdown','rope pushdown','cable pushdown'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Stand at a high pulley with a rope or bar.',
       'Keep the elbows at your sides and extend the arms down.',
       'Return until the forearms are past parallel.'],
 array['Elbows pinned','Squeeze at lockout'],
 array['Leaning over the weight and turning it into a press'],
 12, 15, 75, 60),

('overhead-triceps-extension', 'Overhead Triceps Extension',
 array['overhead extension','french press','cable overhead extension'], 'isolation', 'push', 1, 'beginner', false, false,
 array['Face away from a low pulley or hold a dumbbell overhead.',
       'Keep the upper arms beside the ears and lower behind the head.',
       'Extend back to straight.'],
 array['Upper arms stay put','Get a deep stretch at the bottom'],
 array['Letting the elbows flare wide'],
 10, 15, 75, 170),

-- --- Core --------------------------------------------------------------------
('plank', 'Plank',
 array['front plank','forearm plank'], 'isolation', 'static', 1, 'beginner', false, true,
 array['Set the forearms on the floor under the shoulders.',
       'Brace so the body forms one straight line.',
       'Hold, breathing steadily.'],
 array['Squeeze the glutes','Ribs down, do not sag'],
 array['Holding for time with a sagging lower back'],
 30, 60, 60, 185),

('hanging-leg-raise', 'Hanging Leg Raise',
 array['leg raise','hanging knee raise'], 'isolation', 'pull', 1, 'advanced', false, false,
 array['Hang from a bar with the shoulders active.',
       'Raise the legs until the hips curl up slightly.',
       'Lower with control, without swinging.'],
 array['Curl the pelvis at the top','No swinging between reps'],
 array['Using momentum and only moving at the hip'],
 8, 15, 90, 195),

('cable-crunch', 'Cable Crunch',
 array['kneeling cable crunch','rope crunch'], 'isolation', 'pull', 1, 'beginner', false, false,
 array['Kneel facing away from a high pulley with the rope beside your head.',
       'Crunch down by rounding the spine, not by folding at the hips.',
       'Return under control.'],
 array['Hips stay fixed','Round the spine deliberately'],
 array['Turning it into a hip hinge and working the hip flexors'],
 12, 20, 75, 205),

-- --- Carry / forearms --------------------------------------------------------
('farmer-carry', 'Farmer Carry',
 array['farmers walk','farmer walk','loaded carry'], 'compound', 'static', 2, 'beginner', false, true,
 array['Pick up a heavy dumbbell or kettlebell in each hand.',
       'Stand tall with the shoulders back.',
       'Walk in a straight line for distance or time.'],
 array['Tall posture, do not lean','Crush the handles'],
 array['Letting the shoulders round forward under the load'],
 30, 60, 90, 210)

on conflict (slug) do update
  set name                 = excluded.name,
      aliases              = excluded.aliases,
      mechanic             = excluded.mechanic,
      force                = excluded.force,
      joint_count          = excluded.joint_count,
      difficulty           = excluded.difficulty,
      is_unilateral        = excluded.is_unilateral,
      is_time_based        = excluded.is_time_based,
      instructions         = excluded.instructions,
      cues                 = excluded.cues,
      common_mistakes      = excluded.common_mistakes,
      default_rep_low      = excluded.default_rep_low,
      default_rep_high     = excluded.default_rep_high,
      default_rest_seconds = excluded.default_rest_seconds,
      popularity_rank      = excluded.popularity_rank;
